### ISSUE TITLE
Not able to create the multiple tags with same name but with different parent tag, and category

### ISSUE THREAD

**Issue by Burhanuddin-Nahargarwala** [enqurious/enqurious-platforms-bug-reporting#7]
Steps to Reproduce:

1. Create the tag with the same name, but with different parent tag (or no parent tag), or category
2. Expected Result: The stag should be created under that parent tag
3. Actual Result: It throws the tag already exists error, although parent tag is different

Issue:
We won't be able to create the same tag under multiple categories. Suppose if we have to create pivot tag under python tag, and also under excel tag. It won't allow us to create.

**Comment by Somanadha-Sastry-Konduri** [comment]
@Burhanuddin-Nahargarwala Pivot is a skill, Python and SQL are tools. No matter what tool you use Pivot will be the same skill. So Pivot won't be under SQL or Python, rather it will be under a parent skill called Data Wrangling.

On a broader note. It was intentional that same skill cannot and will not have multiple parents

**Comment by Burhanuddin-Nahargarwala** [comment]
Got it.
